---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresdb-configmap
  namespace: sonarqube
data:
  SONARQUBE_JDBC_USERNAME: postgres
  SONARQUBE_JDBC_URL: "jdbc:postgresql://postgresdb:5432/sonar"
  POSTGRES_USER: postgres
  POSTGRES_DB: sonar
